name: Publish Docker Image
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build master branch for amd64 and push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: '${{ secrets.DOCKERHUB_USERNAME }}/wechat-work-message-push-go:master,ghcr.io/${{ github.actor }}/wechat-work-message-push-go:master'
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Build master branch for multiarch and push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: '${{ secrets.DOCKERHUB_USERNAME }}/wechat-work-message-push-go:master,ghcr.io/${{ github.actor }}/wechat-work-message-push-go:master'
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Get all docker tags
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v3
        id: tags
        with:
          script: |
            const ref = `${context.payload.ref.replace(/\/?refs\/tags\//, '')}`
            const tags = [
              '${{ secrets.DOCKERHUB_USERNAME }}/wechat-work-message-push-go:latest',
              `${{ secrets.DOCKERHUB_USERNAME }}/wechat-work-message-push-go:${ref}`,
              'ghcr.io/${{ github.actor }}/wechat-work-message-push-go:latest',
              `ghcr.io/${{ github.actor }}/wechat-work-message-push-go:${ref}`
            ]
            return tags.join(',')
          result-encoding: string

      # the arm64 is of course much slower due to qemu, so build and push amd64 **first**
      # due to the way manifests work, the gap between this and the complete push below
      #  could result in pull failures or inconsistencies for arm64, such is life.
      # further duplicated by building both release and debug builds
      - name: Build amd64 release and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{steps.tags.outputs.result}}
          cache-from: type=local,src=/tmp/.buildx-cache
          # first run does not export the cache

      - name: Build multiarch release and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{steps.tags.outputs.result}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
